FROM golang:1.22-alpine AS builder

ARG SERVICE_NAME
ARG TARGETARCH=arm64

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /app/cmd/${SERVICE_NAME}
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} go build -ldflags="-s -w" -o worker .

# Final stage - Google Distroless
FROM gcr.io/distroless/static-debian12:latest

WORKDIR /

COPY --from=builder /app/cmd/*/worker /worker

ENTRYPOINT ["/worker"]
